### ISSUE TITLE
something wrong with my computergot     like batch_size=0

### ISSUE THREAD

**Issue by sokigen** [zhunzhong07/CamStyle#3]
(pytorch) D:\test03>python main.py -d market --logs-dir logs/market-ide
Market dataset loaded
  subset   | # ids | # images
  ---------------------------
  train    |     0 |        0
  query    |     0 |        0
  gallery  |     0 |        0
  camstyle  |     0 |        0
Traceback (most recent call last):
  File "main.py", line 198, in <module>
    main(parser.parse_args())
  File "main.py", line 83, in main
    args.width, args.batch_size, args.camstyle, args.re, args.workers)
  File "main.py", line 69, in get_data
    shuffle=True, pin_memory=True, drop_last=True)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 437, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\sampler.py", line 128, in __init__
    "but got batch_size={}".format(batch_size))
ValueError: batch_size should be a positive integeral value, but got batch_size=0

when I ran 'python main.py -d market --logs-dir logs/market-ide' on my computer, I got the information above,what can I do to solove this problem? thank you.

**Comment by zhunzhong07** [comment]
Hi, you should put the dataset in right path. See #2

**Comment by sokigen** [comment]
谢谢您的回复，下载了您提供的数据集的压缩包，解压以后正确的放的位置请问是哪里呢。
![1](https://user-images.githubusercontent.com/28924790/39737441-ad9ad0de-52b7-11e8-8d39-eb2c7c797f11.png)是这样么
![2](https://user-images.githubusercontent.com/28924790/39737443-b3ee8f34-52b7-11e8-9144-3d042819d4c3.png)
还是说是这样
还是说是直接把每个文件夹的图片都丢进去呢？orz 谢谢您的回复，真的帮了大忙

**Comment by zhunzhong07** [comment]
Directory structure

data/
....market/
........query/
........bounding_box_train/

**Comment by sokigen** [comment]
I’m truly grateful for your help.

**Comment by sokigen** [comment]
Hi 
When I enter python `python main.py -d market --logs-dir logs/market-ide-camstyle --camstyle 46
# For Duke` The program just print like this。
`Market dataset loaded
  subset   | # ids | # images
  ---------------------------
  train    |   751 |    12936
  query    |   750 |     3368
  gallery  |   751 |    15913
  camstyle  |     0 |        0
D:\test03\CamStyle\reid\models\resnet.py:49: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(self.feat.weight, mode='fan_out')
D:\test03\CamStyle\reid\models\resnet.py:50: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat.bias, 0)
D:\test03\CamStyle\reid\models\resnet.py:51: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat_bn.weight, 1)
D:\test03\CamStyle\reid\models\resnet.py:52: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat_bn.bias, 0)
D:\test03\CamStyle\reid\models\resnet.py:60: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.classifier.weight, std=0.001)
D:\test03\CamStyle\reid\models\resnet.py:61: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.classifier.bias, 0)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 225, in prepare
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 96, in _run_module_code
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 85, in _run_code
    exitcode = _main(fd)
    exec(code, run_globals)
  File "D:\test03\CamStyle\main.py", line 7, in <module>
    import torch
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 114, in _main
ImportError: DLL load failed: 页面文件太小，无法完成操作。
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
    exitcode = _main(fd)
  File "main.py", line 198, in <module>
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 114, in _main
    main(parser.parse_args())
    prepare(preparation_data)
  File "main.py", line 138, in main
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 225, in prepare
    trainer.train(epoch, train_loader, optimizer)
  File "D:\test03\CamStyle\reid\trainers.py", line 100, in train
    for i, inputs in enumerate(data_loader):
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    prepare(preparation_data)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    run_name="__mp_main__")
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 225, in prepare
    return _DataLoaderIter(self)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 263, in run_path
    w.start()
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    exitcode = _main(fd)
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 114, in _main
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    prepare(preparation_data)
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 225, in prepare
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 96, in _run_module_code
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\test03\CamStyle\main.py", line 7, in <module>
    import torch
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: 页面文件太小，无法完成操作。`

# Could you please tell me how to solve this problem like "ImportError: DLL load failed: 页面文件太小，无法完成操作。"?

**Comment by zhunzhong07** [comment]
Please check if pytorch installed correctly.

**Comment by sokigen** [comment]
Thank you for your  reply.But I have checked my pytorch just like this
![3](https://user-images.githubusercontent.com/28924790/39744612-75daba40-52d7-11e8-818a-ba6f5770a09e.png)
This doesn't seem to be a problem with it。orz。

**Comment by zhunzhong07** [comment]
Does this problem only happen when you run CamStyle? You should also download CamStyle images and put them on the correct path. Please see the preparation in README.

**Comment by CAOXINGWEN** [comment]
> I’m truly grateful for your help.



> I’m truly grateful for your help.

你好，请问这个数据集的路径怎么设置呢，我按照你发的图片还是失败了
